pipeline:
  name: FME-split-evaluator
  identifier: FMEsplitevaluator
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  properties:
    ci:
      codebase:
        connectorRef: splitio
        repoName: split-evaluator
        build:
          type: branch
          spec:
            branch: <+input>
  variables:
    - name: nodeVersions
      type: String
      value: 18.18,22.20,24.10
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          cloneCodebase: true
          runtime:
            type: Cloud
            spec:
              size: small
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  identifier: setup_node
                  name: Setup NodeJS
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu:22.04
                    shell: Bash
                    command: |
                      echo "Installing Node.js version <+matrix.nodeVersion>"
                      apt-get update
                      apt-get install -y curl
                      curl -fsSL https://deb.nodesource.com/setup_<+matrix.nodeVersion>.x | bash -
                      apt-get install -y nodejs npm
                    envVariables:
                      NODE_VERSION: <+matrix.nodeVersion>
                  strategy:
                    matrix:
                      nodeVersion: <+pipeline.variables.nodeVersions.split(",")>
                  timeout: 10m
              - step:
                  type: Run
                  name: Install NPM Dependencies
                  identifier: run_npm_ci
                  spec:
                    runtime:
                      type: SameAsPrevious
                    shell: Bash
                    command: |
                      npm ci
                  timeout: 10m
              - step:
                  type: Run
                  name: NPM Lint
                  identifier: run_npm_lint
                  spec:
                    runtime:
                      type: SameAsPrevious
                    shell: Bash
                    command: |
                      npm run lint
                  timeout: 10m
              - step:
                  type: Run
                  name: Test
                  identifier: run_npm_test
                  spec:
                    shell: Bash
                    command: |
                      apt-get update
                      apt-get install -y nodejs npm
                      npm test
                  timeout: 10m
