pipeline:
  name: FME-split-evaluator
  identifier: FMEsplitevaluator
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build:
          type: branch
          spec:
            branch: main
  variables:
    - name: nodeVersions
      type: String
      value: 18.18,22.20,24.10
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          cloneCodebase: true
          runtime:
            type: Cloud
            spec:
              size: small
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  identifier: setup_node_matrix
                  name: Setup NodeJS Matrix
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu:22.04
                    shell: Bash
                    command: |
                      echo "Installing Node.js version <+matrix.nodeVersion>"
                      apt-get update
                      apt-get install -y curl
                      curl -fsSL https://deb.nodesource.com/setup_<+matrix.nodeVersion>.x | bash -
                      apt-get install -y nodejs
                      node --version
                    envVariables:
                      NODE_VERSION: <+matrix.nodeVersion>
                  strategy:
                    matrix:
                      nodeVersion: <+pipeline.variables.nodeVersions.split(",")>
                  timeout: 10m
              - parallel:
                  - step:
                      type: Run
                      name: Install NPM Dependencies
                      identifier: run_npm_ci
                      spec:
                        connectorRef: account.harnessImage
                        image: ubuntu:22.04
                        shell: Bash
                        command: |
                          npm ci
                        envVariables: {}
                      timeout: 10m
                  - step:
                      type: Run
                      name: Run NPM Lint
                      identifier: run_npm_lint
                      spec:
                        connectorRef: account.harnessImage
                        image: ubuntu:22.04
                        shell: Bash
                        command: |
                          npm run lint
                      timeout: 10m
                  - step:
                      type: Run
                      name: Run NPM Test
                      identifier: run_npm_test
                      spec:
                        connectorRef: account.harnessImage
                        image: ubuntu:22.04
                        shell: Bash
                        command: |
                          npm test
                      timeout: 10m
            rollbackSteps: []
  description: This pipeline was updated by Harness AI on 2026-02-05 15:14:58 UTC by Martin Cardozo.
  tags:
    ai_generated: "true"
