name: cd
on:
  push:
    branches:
      - master

jobs:
  push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: splitio-docker-dev.jfrog.io
          username: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
          password: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build version
        run: echo "BUILD_VERSION=$(cat package.json | grep version | head -1 | awk '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: splitio-docker-dev.jfrog.io/${{ github.event.repository.name }}:latest, splitio-docker-dev.jfrog.io/${{ github.event.repository.name }}:${{ env.BUILD_VERSION}}
