name: test

on:
  pull_request:
    branches-ignore:
      - none

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '18.18'
          - '22.20'
          - '24.10'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js v${{ matrix.version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.version }}

      - run: npm ci
      - run: npm run lint
      - run: npm run test
