name: test

on:
  pull_request:
    branches-ignore:
      - none

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18.18.0

      - run: npm ci
      - run: npm run lint
      - run: npm run test
